---
title: "Prediction systems"
author: "Jagruti"
date: "12/2/2017"
output: html_document
---

```{r,echo = TRUE}
library(ggplot2)
library(dplyr)
library(tm)
library(reshape2)
```

```{r ,echo = TRUE}
x <- read.csv("members.csv")
x[1:2000,]
```

```{r,echo = TRUE}
y <- read.csv ("sample_submission.csv")
y[1:2000,]
```


```{r,echo = TRUE}
z <- read.csv("song_extra_info.csv",header=FALSE, stringsAsFactors=FALSE, fileEncoding="latin1")
z[1:2000,]
```

```{r,echo = TRUE}
w <- read.csv("songs.csv", header=FALSE, stringsAsFactors=FALSE, fileEncoding="latin1")
names(w) = as.character(unlist(w[1,]))
w <- w[-1,]
w[1:2000,]
```

```{r,echo = TRUE}
v <- read.csv("test.csv")
v[1:2000,]
```

```{r,echo = TRUE}
t <- read.csv("train.csv")
t[1:2000,]
```

# Merged train sets
```{r,echo = TRUE}
merger1 <- merge.data.frame(t,w,by = "song_id")
merger_train <- merge.data.frame(merger1,x,by = "msno")
merger_train
```

#Merged test sets
```{r,echo = TRUE}
merger3 <- merge.data.frame(v,w,by = "song_id")
merger_test <- merge.data.frame(merger3,x,by = "msno")
merger_test
```
```{r,echo = TRUE}

ggplot(merger_train)















